package com.classdiagrammer.domain.evidence;

/**
 * Classification of implementation facts per CSAS-002-U2.
 *
 * @author Brandon Martinez - https://github.com/bamartrod
 */
public enum FactKind {
    TYPE_EXISTS,
    DEPENDENCY_EXISTS,
    DEPENDENCY_DIRECTION,
    BOUNDARY_CROSSING,
    INHERITANCE_RELATION,
    INTERFACE_REALIZATION,
    MUTABLE_STATE,
    IMMUTABLE_STATE,
    EXTERNAL_EFFECT,
    CONFIGURATION_DECLARATION,
    CONFIGURATION_CONSUMPTION,
    CONFIGURATION_EFFECT,
    EXCEPTION_BOUNDARY,
    FAILURE_CLASSIFICATION,
    LANGUAGE_FEATURE_USAGE,
    LANGUAGE_FEATURE_AVAILABILITY,
    RESOURCE_OWNERSHIP,
    CONCURRENCY_INTERACTION,
    TEST_ASSOCIATION,
    ARCHITECTURAL_ORIGIN
}
